// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PKMFisipWebsite.Database;

#nullable disable

namespace PKMFisipWebsite.Migrations.AppDbContextBookMigrations
{
    [DbContext(typeof(AppDbContextBook))]
    partial class AppDbContextBookModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("country")
                        .HasColumnType("longtext");

                    b.Property<string>("datePublished")
                        .HasColumnType("longtext");

                    b.Property<string>("desc")
                        .HasColumnType("longtext");

                    b.Property<string>("genre")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("image")
                        .HasColumnType("longblob");

                    b.Property<string>("language")
                        .HasColumnType("longtext");

                    b.Property<int>("mediaType")
                        .HasColumnType("int");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("longtext");

                    b.Property<int>("totalPage")
                        .HasColumnType("int");

                    b.HasKey("bookId");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
