// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PKMFisipWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Author", b =>
                {
                    b.Property<string>("authorId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("authorEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("authorName")
                        .HasColumnType("longtext");

                    b.Property<string>("authorPhone")
                        .HasColumnType("longtext");

                    b.HasKey("authorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Authorship", b =>
                {
                    b.Property<string>("authorshipId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("authorId")
                        .HasColumnType("longtext");

                    b.Property<string>("bookId")
                        .HasColumnType("longtext");

                    b.HasKey("authorshipId");

                    b.ToTable("Authorships");
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("country")
                        .HasColumnType("longtext");

                    b.Property<string>("datePublished")
                        .HasColumnType("longtext");

                    b.Property<string>("desc")
                        .HasColumnType("longtext");

                    b.Property<string>("genre")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("image")
                        .HasColumnType("longblob");

                    b.Property<string>("language")
                        .HasColumnType("longtext");

                    b.Property<int>("mediaType")
                        .HasColumnType("int");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("longtext");

                    b.Property<int>("totalPage")
                        .HasColumnType("int");

                    b.HasKey("bookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BooksPublished", b =>
                {
                    b.Property<string>("booksPublishedId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("bookId")
                        .HasColumnType("longtext");

                    b.Property<string>("publisherId")
                        .HasColumnType("longtext");

                    b.HasKey("booksPublishedId");

                    b.ToTable("BooksPublisheds");
                });

            modelBuilder.Entity("HasRead", b =>
                {
                    b.Property<string>("hasReadId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("bookId")
                        .HasColumnType("longtext");

                    b.Property<string>("lastRead")
                        .HasColumnType("longtext");

                    b.Property<string>("userId")
                        .HasColumnType("longtext");

                    b.HasKey("hasReadId");

                    b.ToTable("HasReads");
                });

            modelBuilder.Entity("IsReading", b =>
                {
                    b.Property<string>("IsReadingId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("bookId")
                        .HasColumnType("longtext");

                    b.Property<string>("lastPage")
                        .HasColumnType("longtext");

                    b.Property<string>("lastRead")
                        .HasColumnType("longtext");

                    b.Property<string>("userId")
                        .HasColumnType("longtext");

                    b.HasKey("IsReadingId");

                    b.ToTable("IsReadings");
                });

            modelBuilder.Entity("Publisher", b =>
                {
                    b.Property<string>("publisherId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("publisherEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("publisherName")
                        .HasColumnType("longtext");

                    b.Property<string>("publisherPhone")
                        .HasColumnType("longtext");

                    b.HasKey("publisherId");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("ReadLater", b =>
                {
                    b.Property<string>("readLaterId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("bookId")
                        .HasColumnType("longtext");

                    b.Property<string>("userId")
                        .HasColumnType("longtext");

                    b.HasKey("readLaterId");

                    b.ToTable("ReadLaters");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext");

                    b.Property<string>("lastName")
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .HasColumnType("longtext");

                    b.Property<string>("userEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("userPhone")
                        .HasColumnType("longtext");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
