// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PKMFisipWebsite.Database;

#nullable disable

namespace PKMFisipWebsite.Migrations.AppDbContextAudioBookMigrations
{
    [DbContext(typeof(AppDbContextAudioBook))]
    partial class AppDbContextAudioBookModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AudioBook", b =>
                {
                    b.Property<int>("audiobookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("audioDatePublished")
                        .HasColumnType("longtext");

                    b.Property<int>("bookId")
                        .HasColumnType("int");

                    b.HasKey("audiobookId");

                    b.ToTable("AudioBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
